name: prophecy_course
description: ''
version: 0.0.1
author: hhau@its.jnj.com
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: prophecycourse
  parentArtefactID: hhauitsjnjcomteam
  buildSystem: wheel
  author: null
  createdAt: '2024-05-30 13:49:18'
pipelines:
  pipelines/enrich_accounts:
    name: enrich_accounts
    description: ''
    author: hhau@its.jnj.com
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-05-30 13:49:18'
    datasets:
      inputs:
      - gitUri=http://gitserver:3000/wvwrv9bI_team_5938/wvwrv9bI_project_13587.git&subPath=&tag=course_lab_sources/0.0.3&projectSubscriptionProjectId=13587&path=datasets/salesforce-Account
      - gitUri=http://gitserver:3000/wvwrv9bI_team_5938/wvwrv9bI_project_13587.git&subPath=&tag=course_lab_sources/0.0.3&projectSubscriptionProjectId=13587&path=datasets/salesforce-Opportunity
      outputs:
      - datasets/enriched_accounts
    subgraphs: []
    dependencies: {}
datasets:
  datasets/enriched_accounts:
    name: enriched_accounts
    description: ''
    author: hhau@its.jnj.com
    createdAt: '2024-05-30 20:45:47'
    mode: batch
    physicalDatasets:
      workshop-fabric:
        fabricId: 12752
        datasetType: Database
        description: ''
        author: hhau@its.jnj.com
        createdAt: '2024-05-30 20:45:47'
templates: {}
jobs:
  jobs/daily_accounts:
    name: daily_accounts
    description: ''
    fabricUID: 12752
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: small
    scheduleCron: 0 0 0 * * ? *
    timeout: null
    alerting:
      emails: hhau@its.jnj.com
      onStart: true
      onSuccess: true
      onFailure: true
    pipelines:
    - pipelines/enrich_accounts
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: true
    createdAt: '2024-05-30 20:51:05'
    author: hhau@its.jnj.com
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-05-30 13:49:18'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- type: plibMaven
  modifiedAt: '2024-05-30T16:00:40.919268Z'
  name: plibMaven
  version: 7.1.102
  id: '1891518992'
  createdAt: '2024-05-30T16:00:40.919199Z'
- type: plibPypi
  modifiedAt: '2024-05-30T16:00:40.919354Z'
  name: plibPypi
  version: 1.8.19
  id: '811365738'
  createdAt: '2024-05-30T16:00:40.919336Z'
projectDependencies:
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.2.14
    isDefault: true
    author: null
    createdAt: '2024-05-30 13:47:42'
  '13587':
    projectUID: 13587
    projectName: course_lab_sources
    repositoryPath: gitUri=http://gitserver:3000/wvwrv9bI_team_5938/wvwrv9bI_project_13587.git&subPath=
    version: course_lab_sources/0.0.3
    isDefault: false
    author: null
    createdAt: '2024-05-30 13:47:42'
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.6
    isDefault: true
    author: null
    createdAt: '2024-05-30 13:47:42'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
